"""TrabajoYunusBDatos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zhWlUes6zHCC9JHmNGMK81TbRjYSJ9is
"""

import pandas as pd
import numpy as np
from pandas import ExcelWriter

"""1. Extraer los datos del excel haciendo uso de python, utilizando la
librería de pandas

"""


df=pd.read_excel("BDatos.xlsx")
df

"""2. Ordenar las columnas por: Nombre, Apellido, Departamento, Sección,
Matrícula, Salario, Fecha ingreso.

"""

df = df[['Nombre','Apellido','Departamento','Sección','Matrícula','Salario','Fecha ingreso']]
df


"""4. Filtrar las columna de sección
Copiadoras
"""

Copiadoras=df[df.Sección == "Copiadoras"]
Copiadoras
df=Copiadoras
print(Copiadoras)

"""Fax"""

Fax=df[df.Sección == "Fax"]
Fax
print(Fax)

"""Impresoras"""


Impresoras=df[df.Sección == "Impresoras"]
Impresoras
print(Impresoras)

"""5. Obtener la suma total de salarios

"""

df['Salario'].sum()

writer = ExcelWriter('ejemplecito.xlsx')
df.to_excel(writer, 'Hoja de datos', index=False)
writer.save()
